swagger: "2.0"
info:
  description: "API responsavel por informações referentes à listas musicais "
  version: "1.0.0"
  title: "Playlist API"
  contact:
    email: "juliana.dallapiculla@gmail.com"
#host: "//localhost:8001/"
basePath: "/playlist/v1"
tags:
- name: "Playlists"
  description: "Tudo sobre playlists"
schemes:
- "http"
paths:
  /playlists:
    get:
      tags:
      - "Playlists"
      summary: ' Buscar playlists musicais tendo o nome da cidade ou sua latitude e longitude como refência.'
      description: | 
        'As listas musicais que serão retornadas para o usuario obecer˜ão a seguinte regra: Se a cidade, no momento da consulta, estiver com temperatura maior que 30ºC, recomenda-se playlists da categoria PARTY. Se a cidade estiver com temperatura entre 15ºC e 30ºC, recomenda-se playlists da categoria POP. Se a temperatura estiver entre 14ºC e 10ºC, recomenda-se playlists da categoria ROCK. Para as demais temperaturas abaixo de 10ºC, recomenda-se playlist da categoria CLASSICAL.'
      produces:
      - "application/json"
      parameters:
      - name: "cityName"
        in: "query"
        description: "Nome da cidade que a ser pesquisada. Este nome pode ser passado tambpem como 'namyCity, countryCode'."
        type: "string"
      - name: "latitude"
        in: "query"
        description: "Coordenada para a cidade."
        type: "number"
      - name: "longitude"
        in: "query"
        description: "Coordenada para a cidade."
        type: "number"
      responses:
        200:
          description: "successful operation"
          schema:
              $ref: "#/definitions/PlaylistResponse"
        400:
          description: "Bad request"
          schema:
            type: array
            items:
              $ref: '#/definitions/Error'

definitions:
  Error:
    type: "object"
    properties:
      code:
        type: "string"
      message:
        type: "string"
  TracksPlaylistResponse:
    type: "object"
    properties:
      playlistCategory: 
        type: string
        example: "party"
      trackNames:
        type: array
        items:
          $ref: '#/definitions/TrackResponse'
  TrackResponse:
    type: object
    properties:
      name:
        type: string
  PlaylistResponse:
    type: "object"
    properties:
      city:
        type: string
        example: 'Campinas'
      temperature:
        type: number
        example: "20.0"
      tracks:
        type: array
        items:
         $ref: "#/definitions/TracksPlaylistResponse"